// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entrenamiento.proto

package um.ssdd.proyecto_ssdd.grpc.entrenamiento;

public interface CrearEntrenamientoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:entrenamiento.CrearEntrenamientoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.entrenamiento.Entrenamiento entrenamiento = 1;</code>
   * @return Whether the entrenamiento field is set.
   */
  boolean hasEntrenamiento();
  /**
   * <code>.entrenamiento.Entrenamiento entrenamiento = 1;</code>
   * @return The entrenamiento.
   */
  um.ssdd.proyecto_ssdd.grpc.entrenamiento.Entrenamiento getEntrenamiento();
  /**
   * <code>.entrenamiento.Entrenamiento entrenamiento = 1;</code>
   */
  um.ssdd.proyecto_ssdd.grpc.entrenamiento.EntrenamientoOrBuilder getEntrenamientoOrBuilder();
}

