// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entrenamiento.proto

package um.ssdd.proyecto_ssdd.grpc.entrenamiento;

/**
 * Protobuf type {@code entrenamiento.CrearEntrenamientoRequest}
 */
public final class CrearEntrenamientoRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:entrenamiento.CrearEntrenamientoRequest)
    CrearEntrenamientoRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CrearEntrenamientoRequest.newBuilder() to construct.
  private CrearEntrenamientoRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CrearEntrenamientoRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CrearEntrenamientoRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CrearEntrenamientoRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            um.ssdd.proyecto_ssdd.grpc.entrenamiento.Entrenamiento.Builder subBuilder = null;
            if (entrenamiento_ != null) {
              subBuilder = entrenamiento_.toBuilder();
            }
            entrenamiento_ = input.readMessage(um.ssdd.proyecto_ssdd.grpc.entrenamiento.Entrenamiento.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(entrenamiento_);
              entrenamiento_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return um.ssdd.proyecto_ssdd.grpc.entrenamiento.EntrenamientoOuterClass.internal_static_entrenamiento_CrearEntrenamientoRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return um.ssdd.proyecto_ssdd.grpc.entrenamiento.EntrenamientoOuterClass.internal_static_entrenamiento_CrearEntrenamientoRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequest.class, um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequest.Builder.class);
  }

  public static final int ENTRENAMIENTO_FIELD_NUMBER = 1;
  private um.ssdd.proyecto_ssdd.grpc.entrenamiento.Entrenamiento entrenamiento_;
  /**
   * <code>.entrenamiento.Entrenamiento entrenamiento = 1;</code>
   * @return Whether the entrenamiento field is set.
   */
  @java.lang.Override
  public boolean hasEntrenamiento() {
    return entrenamiento_ != null;
  }
  /**
   * <code>.entrenamiento.Entrenamiento entrenamiento = 1;</code>
   * @return The entrenamiento.
   */
  @java.lang.Override
  public um.ssdd.proyecto_ssdd.grpc.entrenamiento.Entrenamiento getEntrenamiento() {
    return entrenamiento_ == null ? um.ssdd.proyecto_ssdd.grpc.entrenamiento.Entrenamiento.getDefaultInstance() : entrenamiento_;
  }
  /**
   * <code>.entrenamiento.Entrenamiento entrenamiento = 1;</code>
   */
  @java.lang.Override
  public um.ssdd.proyecto_ssdd.grpc.entrenamiento.EntrenamientoOrBuilder getEntrenamientoOrBuilder() {
    return getEntrenamiento();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (entrenamiento_ != null) {
      output.writeMessage(1, getEntrenamiento());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (entrenamiento_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getEntrenamiento());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequest)) {
      return super.equals(obj);
    }
    um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequest other = (um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequest) obj;

    if (hasEntrenamiento() != other.hasEntrenamiento()) return false;
    if (hasEntrenamiento()) {
      if (!getEntrenamiento()
          .equals(other.getEntrenamiento())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasEntrenamiento()) {
      hash = (37 * hash) + ENTRENAMIENTO_FIELD_NUMBER;
      hash = (53 * hash) + getEntrenamiento().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code entrenamiento.CrearEntrenamientoRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:entrenamiento.CrearEntrenamientoRequest)
      um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return um.ssdd.proyecto_ssdd.grpc.entrenamiento.EntrenamientoOuterClass.internal_static_entrenamiento_CrearEntrenamientoRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return um.ssdd.proyecto_ssdd.grpc.entrenamiento.EntrenamientoOuterClass.internal_static_entrenamiento_CrearEntrenamientoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequest.class, um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequest.Builder.class);
    }

    // Construct using um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (entrenamientoBuilder_ == null) {
        entrenamiento_ = null;
      } else {
        entrenamiento_ = null;
        entrenamientoBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return um.ssdd.proyecto_ssdd.grpc.entrenamiento.EntrenamientoOuterClass.internal_static_entrenamiento_CrearEntrenamientoRequest_descriptor;
    }

    @java.lang.Override
    public um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequest getDefaultInstanceForType() {
      return um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequest.getDefaultInstance();
    }

    @java.lang.Override
    public um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequest build() {
      um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequest buildPartial() {
      um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequest result = new um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequest(this);
      if (entrenamientoBuilder_ == null) {
        result.entrenamiento_ = entrenamiento_;
      } else {
        result.entrenamiento_ = entrenamientoBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequest) {
        return mergeFrom((um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequest other) {
      if (other == um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequest.getDefaultInstance()) return this;
      if (other.hasEntrenamiento()) {
        mergeEntrenamiento(other.getEntrenamiento());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private um.ssdd.proyecto_ssdd.grpc.entrenamiento.Entrenamiento entrenamiento_;
    private com.google.protobuf.SingleFieldBuilderV3<
        um.ssdd.proyecto_ssdd.grpc.entrenamiento.Entrenamiento, um.ssdd.proyecto_ssdd.grpc.entrenamiento.Entrenamiento.Builder, um.ssdd.proyecto_ssdd.grpc.entrenamiento.EntrenamientoOrBuilder> entrenamientoBuilder_;
    /**
     * <code>.entrenamiento.Entrenamiento entrenamiento = 1;</code>
     * @return Whether the entrenamiento field is set.
     */
    public boolean hasEntrenamiento() {
      return entrenamientoBuilder_ != null || entrenamiento_ != null;
    }
    /**
     * <code>.entrenamiento.Entrenamiento entrenamiento = 1;</code>
     * @return The entrenamiento.
     */
    public um.ssdd.proyecto_ssdd.grpc.entrenamiento.Entrenamiento getEntrenamiento() {
      if (entrenamientoBuilder_ == null) {
        return entrenamiento_ == null ? um.ssdd.proyecto_ssdd.grpc.entrenamiento.Entrenamiento.getDefaultInstance() : entrenamiento_;
      } else {
        return entrenamientoBuilder_.getMessage();
      }
    }
    /**
     * <code>.entrenamiento.Entrenamiento entrenamiento = 1;</code>
     */
    public Builder setEntrenamiento(um.ssdd.proyecto_ssdd.grpc.entrenamiento.Entrenamiento value) {
      if (entrenamientoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        entrenamiento_ = value;
        onChanged();
      } else {
        entrenamientoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.entrenamiento.Entrenamiento entrenamiento = 1;</code>
     */
    public Builder setEntrenamiento(
        um.ssdd.proyecto_ssdd.grpc.entrenamiento.Entrenamiento.Builder builderForValue) {
      if (entrenamientoBuilder_ == null) {
        entrenamiento_ = builderForValue.build();
        onChanged();
      } else {
        entrenamientoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.entrenamiento.Entrenamiento entrenamiento = 1;</code>
     */
    public Builder mergeEntrenamiento(um.ssdd.proyecto_ssdd.grpc.entrenamiento.Entrenamiento value) {
      if (entrenamientoBuilder_ == null) {
        if (entrenamiento_ != null) {
          entrenamiento_ =
            um.ssdd.proyecto_ssdd.grpc.entrenamiento.Entrenamiento.newBuilder(entrenamiento_).mergeFrom(value).buildPartial();
        } else {
          entrenamiento_ = value;
        }
        onChanged();
      } else {
        entrenamientoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.entrenamiento.Entrenamiento entrenamiento = 1;</code>
     */
    public Builder clearEntrenamiento() {
      if (entrenamientoBuilder_ == null) {
        entrenamiento_ = null;
        onChanged();
      } else {
        entrenamiento_ = null;
        entrenamientoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.entrenamiento.Entrenamiento entrenamiento = 1;</code>
     */
    public um.ssdd.proyecto_ssdd.grpc.entrenamiento.Entrenamiento.Builder getEntrenamientoBuilder() {
      
      onChanged();
      return getEntrenamientoFieldBuilder().getBuilder();
    }
    /**
     * <code>.entrenamiento.Entrenamiento entrenamiento = 1;</code>
     */
    public um.ssdd.proyecto_ssdd.grpc.entrenamiento.EntrenamientoOrBuilder getEntrenamientoOrBuilder() {
      if (entrenamientoBuilder_ != null) {
        return entrenamientoBuilder_.getMessageOrBuilder();
      } else {
        return entrenamiento_ == null ?
            um.ssdd.proyecto_ssdd.grpc.entrenamiento.Entrenamiento.getDefaultInstance() : entrenamiento_;
      }
    }
    /**
     * <code>.entrenamiento.Entrenamiento entrenamiento = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        um.ssdd.proyecto_ssdd.grpc.entrenamiento.Entrenamiento, um.ssdd.proyecto_ssdd.grpc.entrenamiento.Entrenamiento.Builder, um.ssdd.proyecto_ssdd.grpc.entrenamiento.EntrenamientoOrBuilder> 
        getEntrenamientoFieldBuilder() {
      if (entrenamientoBuilder_ == null) {
        entrenamientoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            um.ssdd.proyecto_ssdd.grpc.entrenamiento.Entrenamiento, um.ssdd.proyecto_ssdd.grpc.entrenamiento.Entrenamiento.Builder, um.ssdd.proyecto_ssdd.grpc.entrenamiento.EntrenamientoOrBuilder>(
                getEntrenamiento(),
                getParentForChildren(),
                isClean());
        entrenamiento_ = null;
      }
      return entrenamientoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:entrenamiento.CrearEntrenamientoRequest)
  }

  // @@protoc_insertion_point(class_scope:entrenamiento.CrearEntrenamientoRequest)
  private static final um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequest();
  }

  public static um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CrearEntrenamientoRequest>
      PARSER = new com.google.protobuf.AbstractParser<CrearEntrenamientoRequest>() {
    @java.lang.Override
    public CrearEntrenamientoRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CrearEntrenamientoRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CrearEntrenamientoRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CrearEntrenamientoRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public um.ssdd.proyecto_ssdd.grpc.entrenamiento.CrearEntrenamientoRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

