// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entrenamiento.proto

package um.ssdd.proyecto_ssdd.grpc.entrenamiento;

public interface EntrenamientoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:entrenamiento.Entrenamiento)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
